### ISSUE TITLE
[Enhancement] scan logo mid?

### ISSUE THREAD

**Issue by HasanY1989** [Fiaxhs/pgmap#22]
First of all, great job @Fiaxhs , you very helpful and doing a great job. 
And to all the contributes, especial @BenoitZugmeyer who just added multi user and going for multi account.

Our small town who uses this via my localhost loves this.

However how can I make the scan logo going mid instead of left corner, what do i need to edit in the code, any help would be great :-) 
- Edit, will the radius be bigger after multi account add?
  Thanks

**Comment by BenoitZugmeyer** [comment]
[Those lines](https://github.com/BenoitZugmeyer/pgmap/blob/cfe1880c18ffd0c9ab3e9e4e53b95f5fd83bbdbc/src/app.js#L146-L151) are responsible for the 9 by 9 grid pattern the crawler is doing. You can change those if you want to.

The multi-account does not change this behavior. However, I am planning to implement a smarter crawling behavior next, based on the last crawled date of a cell instead of the current hardcoded pattern.

**Comment by Fiaxhs** [comment]
I believe he's talking about the button itself.

**Comment by HasanY1989** [comment]
Yea, im guessing the button can be adjutst by the css and html. 

As for the bigger radius, im guessing those line you just potsed need to get chnaged, so its bigger. 

However you current crawler gives me a error, and takes server down after 5 min even when used. 
I will try to test it with screenshot, when i come home show you  the errors it give.

**Comment by Fiaxhs** [comment]
@HasanY1989 You can change the radius shown on the  map, but it won't change what is actually scanned, this area is defined by niantic.

**Comment by HasanY1989** [comment]
Yea i noticed that mate
/closed
